name: semantic_mapping
channels:
  - https://anaconda.org/pytorch3d/pytorch3d/0.7.4/download
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.10.0=py310h06a4308_0
  - aom=3.12.1=h7934f7d_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py310hee96239_0
  - asttokens=3.0.0=py310h06a4308_0
  - async-lru=2.0.5=py310h06a4308_0
  - attrs=25.4.0=py310h06a4308_2
  - babel=2.17.0=py310h06a4308_0
  - beautifulsoup4=4.14.2=py310h06a4308_0
  - blas=1.0=mkl
  - bleach=6.3.0=py310h06a4308_0
  - bottleneck=1.4.2=py310haa0f9ac_1
  - brotlicffi=1.1.0.0=py310hbdd6827_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=py310h06a4308_0
  - cffi=1.15.1=py310h74dc2b5_0
  - charset-normalizer=3.4.4=py310h06a4308_0
  - comm=0.2.3=py310h06a4308_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.9=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.16=py310hbdd6827_1
  - decorator=5.2.1=py310h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.3.0=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ffmpeg=6.1.1=hecf7045_5
  - filelock=3.20.0=py310h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py310hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.16.0=py310h06a4308_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py310h06a4308_0
  - httpx=0.28.1=py310h06a4308_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py310h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=6.31.0=py310h7040dfc_0
  - ipython=8.30.0=py310h06a4308_0
  - ipython_pygments_lexers=1.1.1=py310h06a4308_0
  - ipywidgets=8.1.7=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - jinja2=3.1.6=py310h06a4308_0
  - joblib=1.5.2=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - json5=0.12.1=py310h06a4308_0
  - jsonschema=4.25.0=py310h06a4308_1
  - jsonschema-specifications=2025.9.1=py310h06a4308_0
  - jupyter=1.1.1=py310h06a4308_0
  - jupyter-lsp=2.2.5=py310h06a4308_0
  - jupyter_client=8.6.3=py310h06a4308_1
  - jupyter_console=6.6.3=py310h06a4308_0
  - jupyter_core=5.8.1=py310h06a4308_0
  - jupyter_events=0.12.0=py310h06a4308_0
  - jupyter_server=2.16.0=py310h06a4308_0
  - jupyter_server_terminals=0.5.3=py310h06a4308_0
  - jupyterlab=4.4.7=py310h06a4308_0
  - jupyterlab_pygments=0.3.0=py310h06a4308_0
  - jupyterlab_server=2.28.0=py310h06a4308_0
  - jupyterlab_widgets=3.0.15=py310h06a4308_0
  - kiwisolver=1.4.9=py310h24d9097_0
  - krb5=1.21.3=h723845a_4
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.14.1.1=4
  - libcups=2.4.2=h252cb56_2
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libegl-devel=1.7.0=h5eee18b_2
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libgl-devel=1.7.0=h5eee18b_2
  - libglib=2.84.4=h77a78f3_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libglx-devel=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm14=14.0.6=hecde1de_4
  - libllvm15=15.0.7=he89c38a_4
  - libnpp=11.8.0.86=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjpeg=11.9.0.86=0
  - libogg=1.3.5=h27cfd23_1
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.1=h029b1ac_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.15.2=h4cb591d_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib=3.10.6=py310h06a4308_1
  - matplotlib-base=3.10.6=py310h71dd3da_1
  - matplotlib-inline=0.2.1=py310h06a4308_0
  - mesalib=25.1.5=h31e3550_0
  - mistune=3.1.2=py310h06a4308_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py310hacdc0fc_0
  - mkl_fft=2.1.1=py310h8fe796d_0
  - mkl_random=1.3.0=py310h505adc9_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - mysql=9.3.0=hef88997_3
  - mysql-client=9.3.0=h453df32_3
  - mysql-common=9.3.0=h0021b1a_3
  - mysql-devel=9.3.0=h0021b1a_3
  - mysql-libs=9.3.0=h797a5cd_3
  - mysql-server=9.3.0=hefcd325_3
  - nbclient=0.10.2=py310h06a4308_0
  - nbconvert=7.16.6=py310h06a4308_0
  - nbconvert-core=7.16.6=py310h06a4308_0
  - nbconvert-pandoc=7.16.6=py310h06a4308_0
  - nbformat=5.10.4=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - networkx=3.4.2=py310h06a4308_0
  - notebook=7.4.5=py310h06a4308_0
  - notebook-shim=0.2.4=py310h06a4308_0
  - numexpr=2.14.1=py310h41d4191_0
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.4=h4e0627c_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.0.18=hd6dcaed_0
  - overrides=7.7.0=py310h06a4308_0
  - packaging=25.0=py310h06a4308_1
  - pandas=2.3.3=py310h23c847b_1
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py310h06a4308_0
  - parso=0.8.5=py310h06a4308_0
  - pcre=8.45=h295c915_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=py310h06a4308_1
  - pillow=11.1.0=py310hac6e08b_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=py310h06a4308_0
  - prometheus_client=0.21.1=py310h06a4308_0
  - prompt-toolkit=3.0.52=py310h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py310hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310h06a4308_0
  - pycparser=2.23=py310h06a4308_0
  - pygments=2.19.2=py310h06a4308_0
  - pyparsing=3.2.5=py310h06a4308_0
  - pyqt=6.9.1=py310hc79087c_0
  - pyqt5-sip=12.17.0=py310hee96239_0
  - pyqt6-sip=13.10.2=py310hee96239_0
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-fastjsonschema=2.21.2=py310h06a4308_0
  - python-json-logger=3.2.1=py310h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.4=py310_cu118_pyt201
  - pytz=2025.2=py310h06a4308_0
  - pyyaml=6.0.3=py310h591646f_0
  - pyzmq=27.1.0=py310hcf8288c_1
  - qt-main=6.9.2=ha538ae8_0
  - qt5compat=6.9.2=ha155076_1
  - qtbase=6.9.2=hd13baf8_5
  - qtbase-devel=6.9.2=hfd094ee_5
  - qtconsole=5.7.0=py310h06a4308_0
  - qtdeclarative=6.9.2=h55666de_1
  - qtimageformats=6.9.2=h8797ac5_1
  - qtpy=2.4.3=py310h06a4308_0
  - qtshadertools=6.9.2=hbdd6827_1
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_1
  - qttranslations=6.9.2=hbdd6827_1
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=py310h06a4308_0
  - requests=2.32.5=py310h06a4308_1
  - rfc3339-validator=0.1.4=py310h06a4308_0
  - rfc3986-validator=0.1.1=py310h06a4308_0
  - rpds-py=0.28.0=py310h498d7c9_0
  - scikit-learn=1.7.2=py310h505adc9_0
  - scipy=1.15.3=py310h0a862cd_1
  - send2trash=1.8.2=py310h06a4308_1
  - setuptools=80.9.0=py310h06a4308_0
  - sip=6.12.0=py310h7934f7d_0
  - six=1.17.0=py310h06a4308_0
  - sniffio=1.3.0=py310h06a4308_0
  - soupsieve=2.5=py310h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=py310h06a4308_0
  - sympy=1.14.0=py310h06a4308_0
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - terminado=0.18.1=py310h06a4308_0
  - tesseract=5.2.0=hb0d2e87_3
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tinycss2=1.4.0=py310h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py310h06a4308_0
  - tornado=6.5.1=py310h5eee18b_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py310h06a4308_0
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.2.13=py310h06a4308_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=1.8.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - widgetsnbextension=4.0.14=py310h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - blinker==1.9.0
      - click==8.3.1
      - clip==1.0
      - conceptgraph==1.0.0
      - configargparse==1.7.1
      - dash==3.3.0
      - dill==0.4.0
      - distinctipy==1.3.4
      - distro==1.9.0
      - docstring-parser==0.17.0
      - faiss-gpu==1.7.2
      - flask==3.1.2
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - groq==0.36.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - jiter==0.12.0
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lazy-loader==0.4
      - markdown==3.10
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - narwhals==2.12.0
      - natsort==8.4.0
      - numpy==1.26.4
      - nvidia-cublas==13.0.0.19
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile==1.15.0.42
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand==10.4.0.35
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - open-clip-torch==3.2.0
      - open3d==0.19.0
      - openai==2.8.1
      - opencv-python==4.11.0.86
      - plotly==6.5.0
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyliblzfse==0.4.1
      - pypng==0.20220715.0
      - pyquaternion==0.9.9
      - regex==2025.11.3
      - retrying==1.4.2
      - rich==14.2.0
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-video==1.1.11
      - sentencepiece==0.2.1
      - sentry-sdk==2.46.0
      - shtab==1.8.0
      - smmap==5.0.2
      - supervision==0.27.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tifffile==2025.5.10
      - timm==1.0.22
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.5.1
      - typeguard==4.4.4
      - typing-inspection==0.4.2
      - tyro==0.9.35
      - ultralytics==8.3.232
      - ultralytics-thop==2.0.18
      - wandb==0.23.0
      - werkzeug==3.1.3
      - zipp==3.23.0
